config/routes.rb
Blog::Application.routes.draw do
  root to: 'posts#index'

  get 'admin',to: 'sessions#new'
  match 'admin',via: :post,to: 'sessions#create'
  match 'admin',via: :delete,to: 'sessions#destroy'

  resources :tags ,only: [:index,:show]

  resources :posts do
    resources :comments,only: [:create,:destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post,counter_cache: true
  attr_accessible :body, :email, :ip, :name

  validates :name,presence: true
  validates :name,length: 1..10,allow_nil: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence: true
  validates :email,format: {with: VALID_EMAIL_REGEX},allow_nil: true
  validates :body,presence: true
  validates :body,length: 1..200,allow_nil: true

  default_scope order("created_at")
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title

  validates :title,presence: true,uniqueness: true
  validates :body,presence: true

  has_many :comments,dependent: :destroy
  has_many :tags,dependent: :destroy

  default_scope order("created_at DESC")
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name

  validates :name,presence: true

  def self.tags
    select("distinct name,count(tags.name)").order("count(tags.name) DESC").group "tags.name"
  end

  def self.find_tags_by_name name
    where "name = ?",name
  end

  def self.top n
    tags.limit n
  end

  def tag_count
    Tag.find_tags_by_name(name).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :gener_authentication_token

  has_secure_password
  attr_accessible :email,:name,:password,:password_confirmation

  validates :name,presence: true,length: 1..20
  validates :email,presence: true,uniqueness: {case_sensitive: false},format: {with: Comment::VALID_EMAIL_REGEX}
  validates :password,presence: true,length:6..20
  validates :password_confirmation,presence: true

  private
    def gener_authentication_token
      self.authentication_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
  include ApplicationHelper
end

app/controllers/comments_controller.rb
#coding:utf-8
class CommentsController < ApplicationController

  before_filter :check_role,only: [:destroy]

  cache_sweeper :comment_sweeper

  def create
    @post = Post.find_by_id params[:post_id]
    @comment = @post.comments.build params[:comment]

    @comment.toggle :by_admin if admin?
    @comment.ip = request.remote_ip

    if @comment.save
      Thread.new{CommentNotify.new_comment(@comment).deliver} unless @comment.by_admin?
      redirect_to @post
    else
      @comments = @post.comments.all
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = @post.comments.find params[:id]
    @comment.destroy
    flash["success"] = "已删除 #{@comment.name} 的评论"
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :check_role,only: [:new,:edit,:create,:update,:destroy]
  cache_sweeper :post_sweeper,:tag_sweeper

  # GET /posts
  # GET /posts.json
  def index
    unless fragment_exist? "posts#index#{admin?}",page: params[:page] || 1
      @posts = Post.paginate page: params[:page]
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    unless fragment_exist?("posts#show#{params[:id]}") && fragment_exist?("posts#show#comments#{params[:id]}")
      @post = Post.find(params[:id]) 
      @comments = @post.comments.all
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id]) unless fragment_exist? "posts#edit#{params[:id]}"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    if @post.save
      if tags = params[:tags]
        add_tags @post,tags
      end
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      if tags = params[:tags]
        update_tags @post,tags
      end
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url
  end
end

app/controllers/sessions_controller.rb
#coding:utf-8
class SessionsController < ApplicationController

  before_filter :check_login,only: [:new,:create]
  before_filter :check_role,only: :destroy

  def new
  end

  def create
    unless verify_recaptcha
      flash.now["error"] = "验证码错误"
      render :new
      return
    end
    @user = User.find_by_email params[:session][:email]
    if @user && @user.authenticate(params[:session][:password])
      reset_session
      sign_in @user,params[:remember]
      flash["success"] = "login success"
      redirect_to root_path
    else
      flash.now["error"] = "email/password invalid!"
      render :new
    end
  end

  def destroy
    logout
    flash["info"] = "logout"
    redirect_to root_path
  end

  private
    def check_login
      if admin?
        flash["info"] = "You having be login"
        redirect_to root_path
      end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    unless fragment_exist? 'tags#index',page: params[:page] || 1
      @tags = Tag.tags.paginate page: params[:page]
    end
  end

  def show
    unless fragment_exist? "tags#show#{params[:id]}",page: params[:page] || 1
      @tags = Tag.find_tags_by_name(params[:id]).includes(:post).paginate page: params[:page]
      @posts = @tags.map &:post
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  TIME_ZONE = "Beijing"

  include PostsHelper

  def full_title title = nil
    unless title.blank?
      "#{title} | Ruby-Tips"
    else
      "Ruby-Tips"
    end
  end

  def tags_count
    Tag.tags.length
  end

  def format_date date
    date.localtime.in_time_zone(ApplicationHelper::TIME_ZONE).strftime "%Y-%m-%d %H:%M:%S"
  end

  def admin_user
    @admin_user ||= User.first
  end

  def markdown text
    options = {autolink: true,space_after_headers: true,fenced_code_blocks: false,no_intra_emphasis: true,hard_wrap: true,strikethrough: true}
    markdown = Redcarpet::Markdown.new HTMLwithCodeRay,options
    markdown.render(text).html_safe
  end

  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code code,language
      CodeRay.scan(code,language).div tab_width: 2
    end
  end
end

app/helpers/comments_helper.rb
require 'digest/md5'
module CommentsHelper
  def gravatar_url_for email,opt = {size: 40}
    "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email.strip.downcase)}?s=#{opt[:size]}"
  end

  def gravatar_for email,opt = {size: 50}
    gravatar_url = gravatar_url_for email,opt
    link_to image_tag(gravatar_url,height: opt[:size],width: opt[:size],alt: "Icon"),gravatar_url,class: "thumbnail"
  end

  def comment_number
    @comment_number = 0 if @comment_number.nil?
    @comment_number += 1
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  TAGS_REGEX = /[\s,]+/

  def show_tags post
    if tags = post.tags
      tags.map(&:name).join ", "
    end
  end

  def split_tags tags
    tags.split TAGS_REGEX
  end


  def update_tags post,tags
    tags = split_tags(tags).map do |tag|
      post.tags.build name: tag
    end
    @post.tags = tags
    @post.save
  end

  alias add_tags update_tags
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user= user
    @current_user = user
  end

  def sign_in user,remember
    if remember
      cookies.permanent[:authentication_token] = user.authentication_token
    else
      cookies[:authentication_token] = user.authentication_token
    end
    self.current_user = user
  end

  def current_user
    @current_user ||= User.find_by_authentication_token(cookies[:authentication_token])
  end

  def admin?
    !current_user.nil?
  end

  def logout
    self.current_user = nil
    cookies.delete :authentication_token
  end


  private
    def check_role
      unless admin?
        redirect_to root_path
      end
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comment_notify/new_comment.html.erb
<p>
<%=@comment.name%> 评论了 <%=@comment.post.title%>
<p/>
<div class="comment-main">
  <div class="comment-info">
    <div class="comment-icon">
      <%= gravatar_for @comment.email%>
    </div>
    <div class="comment-name">
      <%= link_to @comment.name,"mailto:#{@comment.email}"%>
    </div>
  </div>
  <div class="comment-body">
    <div class="comment-content">
      <%= markdown @comment.body%>
    </div>
    <br />
    <span class="comment-time"><%= format_date @comment.created_at%></span><br />
  </div>
</div>
<br />

app/views/comments/_comment.html.erb
<comment>
<div class="comment-main<%= " comment-admin" if comment.by_admin? %>" id="c<%= comment_num = comment_number%>">
<div class="comment-info">
  <div class="comment-icon">
    <%= gravatar_for comment.email%>
  </div>
<div class="comment-name" id="cname<%=comment_num%>" cname="<%=comment.name%>">
  <% if admin? %>
    <%= link_to comment.name,"mailto:#{comment.email}"%>
  <% else %>
    <%=comment.name%>
  <% end%>
</div>
</div>
<div class="comment-body">
  <a class="comment-ref" href="javascript:ref_comment(<%=comment_num%>)">引用</a>
  <span class="comment-number">#<%=comment_num %></span>
  <br />
  <div class="comment-content" id="cbody<%=comment_num%>">
      <%= markdown comment.body%>
  </div>
  <br />
  <span class="comment-time"><%= format_date comment.created_at%></span><br />
</div>
<% if admin?%>
  <%= link_to 'delete',[comment.post,comment],method: :delete,confirm: "You sure?",class:"comment-delete"%>
<% end%>
</div>
<br />
<hr />
</comment>

app/views/comments/_form.html.erb
<div class="comment-form">
<% if @comment && @comment.errors.any?%>
  <div class="alert alert-error">
    <ul>
      <% @comment.errors.full_messages.each do |m| %>
        <li><%=m%></li>
      <% end%>
    <ul>
  </div>
<% end%>
<%= form_for [@post,@comment || @post.comments.build] do |f| %>
  <%= f.label :name,'昵称:' %>
  <% if admin? %>
    <%= f.text_field :name,value: current_user.name %>
  <% else %>
    <%= f.text_field :name %>
  <% end %>
  <br />
    <%= f.label :email %>
  <% if admin? %>
    <%= f.text_field :email,value: current_user.email %>
  <% else %>
    <%= f.text_field :email %>
  <% end%>
  <br />
  <p>
  <%= f.label :body,'评论:'%>
  *支持markdown格式
  <br/>
  <%= f.text_area :body,class: "comment-form-body", id: "comment_form_body"%>
  </p>
  <%= f.submit%>
<% end%>
</div>

app/views/layouts/_detial.html.erb
<%cache 'detail' do%>
  <div>
    <detail>
    <h3>统计</h3>
    <hr />
    <ul>
      <li>文章数 <%= Post.all.count%></li>
      <li>回复数 <%= Comment.all.count%></li>
      <li>Tags <%= tags_count%></li>
    </ul>
    </detail>
  </div>
<%end%>

app/views/layouts/_footer.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34340016-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path%>">
        Ruby-Tips
      </a>
      <ul class="nav">
        <li>
          <a href="<%= root_path%>">Home</a>
        </li>
        <li>
          <a href="<%= tags_path %>">Tags</a>
        </li>
        <% if admin?%>
          <li>
            <%= link_to 'Logout',admin_path,method: :delete,class: "logout"%>
          <li/>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_info.html.erb
<div class="content admininfo">
  <%= render 'users/user' %>
</div>
<div class="content statistic">
  <%=render 'layouts/detial' %>
</div>
<div class="content top">
  <%=render 'tags/tags' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag gravatar_url_for(admin_user.email)%>
</head>
<body class="body-style">
<%= render 'layouts/header'%>

<div class="container">
  <% flash.each do |key,value|%>
    <%=content_tag :div,value, class: "alert alert-#{key}"%>
  <% end%>
  <div id="main" class="row">
    <div class="content span8">
      <%=yield %>
    </div>
    <div class="span3 offset1">
      <%= render 'layouts/info' %>
    </div>
  </div>
</div>

<%= render 'layouts/footer'%>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="tags">Tags</label>
    <input id="tags" name="tags" type="text" value="<%=show_tags @post%>" />
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.kindeditor :body,input_html: {width: 400,height: 200},allowFileManager: false%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
<span class="replies-count"><%=pluralize post.comments_count,'reply'%></span>
<span class="post-title"><%= link_to post.title,post %></span>
<p class="post-body"><%= truncate strip_tags(post.body),length: 200 %></p>
<p class="date"><%=format_date post.created_at%></p>
<% if admin? %>
  <span><%= link_to 'Edit', edit_post_path(post) %></span>
  <span><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></span>
<% end%>
</li>
<% if post.tags.any? %>
  <div class="post-tags">
    <% post.tags.each do |tag|%>
      <%= link_to content_tag(:span,tag.name,class: "label"),tag_path(tag.name),class: "post-tag"%>
    <% end%>
  </div>
<% end %>
<br />
<hr />

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div>
  <%cache "posts#index#{admin?}",page: params[:page] || 1 do%>
    <posts>
    <ul>
      <%=render @posts%>
    </ul>
    </posts>
    <p>
    <%=will_paginate%>
    </p>
    <br />
  <%end%>

  <% if admin? %>
    <%= link_to 'New Post', new_post_path %>
  <% end%>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%cache "posts#show#{params[:id]}#{admin?}" do%>
  <%provide :title,@post.title%>

  <post>
  <div class="post-title">
    <h1>
      <%= @post.title %>
    </h1>
  </div>

  <div class="post-body">
    <%= raw @post.body %>
  </div>
  <span class="date"><%=format_date @post.created_at%></span>
<%end%>
<% if admin? %>
  <%= link_to 'Edit', edit_post_path(@post) %>
  <post>
<% end %>
<br />
<hr />
<%cache "posts#show#comments#{params[:id]}#{admin?}" do%>
  <%=render @comments%>
  <p>
  </p>
  <%=render 'comments/form'%>
<%end%>

app/views/tags/_tag.html.erb
<hr />
<p class="tags-tag">
  <%=link_to tag.name,tag_path(tag.name)%>(<%=tag.tag_count%>)
</p>

app/views/tags/_tags.html.erb
<%cache 'tags#top' do%>
  <% @tags = Tag.top 10 %>
  <h3>Top 10 tags</h3>
  <hr />
  <% if @tags.any? %>
    <ul>
      <% @tags.each do |tag|%>
        <li>
        <%=link_to tag.name,tag_path(tag.name)%>(<%=tag.tag_count%>)
        </li>
      <% end%>
    </ul>
  <% end%>
<%end%>

app/views/tags/index.html.erb
<%provide :title,"Tags"%>
<%cache 'tags#index',page: params[:page] || 1 do %>
  <tags>
  <div>
    <span>Tags</span>
    <p>
    <%=render @tags%>
    </p>
  </div>
  <tags>
  <%= will_paginate%>
<%end%>

app/views/tags/show.html.erb
<% provide(:title,tag_name = params[:id])%>
<%cache "tags#show#{params[:id]}",page: params[:page] || 1 do%>
  <div>
    <span class="tag-title"><%=tag_name%></span>
    <hr />
    <posts>
    <ul>
      <%= render @posts %>
    </ul>
    </posts>
  </div>
  <p>
  <%=will_paginate%>
  </p>
<%end%>

app/views/users/_user.html.erb
<%cache "users#show" do%>
  <admin>
  <h3>Blog info</h3>
  <hr />
  <div class="admin-icon" ><%=gravatar_for admin_user.email,size:80 %></div>
  <div class="admin-info">
    <h3 class="admin-name"><%= link_to admin_user.name, "mailto:#{admin_user.email}"%></h3><br />
    <span class="admin-link"><a href="http://github.com/<%= admin_user.name%>">My github</a></span>
  </div>
  </admin>
<%end%>